//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToskanaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientForDish
    {
        public int iD { get; set; }
        public Nullable<int> IngredientID { get; set; }
        public Nullable<int> DishID { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
