//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToskanaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> DishID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> AutorID { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Employe Employe { get; set; }
    }
}
